### ISSUE TITLE
Remove extra whitespace above H2 

### ISSUE THREAD

**Issue by melissahsiung** [climateaction-tech/climateAction-wordpress#1]
Example: Home page above "Our Focus Areas" and "We Are Just Getting Started". Should be ~80px. Currently ~150px.

On desktop, Chrome.

**Comment by hanopcan** [comment]
We talked about this on Slack and it's sorted now.

Melissa, I made a utility class that you can apply to any gutenberg block to help with this in future.

Apply `pt-0` to remove the top margin.
