### ISSUE TITLE
Main action page: add dropshadows to action preview tiles

### ISSUE THREAD

**Issue by melissahsiung** [climateaction-tech/climateAction-wordpress#2]
Match the style of the tiles on the [Resources page](https://climateaction.tech/resources/):

`#wp-block-themeisle-blocks-advanced-column-5b9b1227 {
    padding-top: 32px;
    padding-right: 20px;
    padding-bottom: 0;
    padding-left: 20px;
    margin-top: 8px;
    margin-right: 8px;
    margin-bottom: 8px;
    margin-left: 8px;
    border-width: 0;
    border-style: solid;
    border-color: #000;
    border-radius: 8px;
    box-shadow: 0px 0px 16px 4px rgba(0,0,0,.16);`

**Comment by hanopcan** [comment]
@melissahsiung I've made some amends and added it straight to live. I think the action teaser boxes look better, but still not quite right.  Stefanie said she was going to come up with some designs for these that hopefully I can implement next week. Let me know of you think anything is really awful and needs sorting straight away - I will do my best!
