### ISSUE TITLE
Main Actions page title

### ISSUE THREAD

**Issue by melissahsiung** [climateaction-tech/climateAction-wordpress#3]
https://climateaction.tech/actions/
Change from "Actions Archive" to "Actions". Or "Action Guides" maybe?

**Comment by hanopcan** [comment]
@melissahsiung asked for feedback on the names in this Slack comment:

https://climate-tech.slack.com/archives/CGNDA83TL/p1611324613001600

The popular vote seemed to be 'Action Guide'.

So I have updated the browser tab title to be `Action Guides.`

![Action Guides browser tab title](https://user-images.githubusercontent.com/11687898/105515197-4f647700-5ccc-11eb-817f-fc31fd49a59d.jpg)
